# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
               [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               
                [[10,11,12],
                [13,14,15],
                [16,17,18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.shape, a1.size, type(a1)

(1, dtype('int32'), (3,), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.shape, a2.size, type(a2)

(2, dtype('int32'), (2, 3), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.shape, a3.size, type(a3)

(3, dtype('int32'), (2, 3, 3), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a2_df = pd.DataFrame(a2)
a2_df

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr2 = np.random.randint(0,10,size=(7,2))

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr3 = np.random.random((3,5))
arr3

array([[0.38061752, 0.29806111, 0.90938045, 0.16903906, 0.45093146],
       [0.63448853, 0.02402302, 0.70572006, 0.1674754 , 0.64609705],
       [0.35364156, 0.76353815, 0.67479739, 0.85424838, 0.0422178 ]])

In [12]:
# Set the random seed to 42
np.random.seed(seed = 42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr4 = np.random.randint(0,10,size=(4,6))
arr4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr5 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(arr5)

array([1, 2, 3, 4, 5, 7, 9])

In [14]:
arr5

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [15]:
arr5.shape, arr5.ndim

((3, 7), 2)

In [16]:
# Find the 0'th index of the latest array you created
arr5[0][0]

9

In [17]:
# Get the first 2 rows of latest array you created
arr5[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [18]:
# Get the first 2 values of the first 2 rows of the latest array
arr5[:2,:2]

array([[9, 1],
       [5, 3]])

In [19]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr6 = np.random.randint(0,10,size = (3,5))
arr7 = np.ones((3,5))

In [20]:
arr6

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [21]:
arr7

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Add the two arrays together
np.add(arr6, arr7)

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [23]:
# Create another array of ones of shape (5, 3)
arr8 = np.ones((5, 3))

In [24]:
# Try add the array of ones and the other most recent array together
# np.add(arr8, arr6)

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [25]:
# Create another array of ones of shape (3, 5)
arr9 = np.ones((3, 5))

In [26]:
# Subtract the new array of ones from the other most recent array
arr10 = arr6 - arr9
arr10

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [27]:
# Multiply the ones array with the latest array
arr10 * arr9

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [28]:
# Take the latest array to the power of 2 using '**'
arr10 ** 2

array([[25., 36.,  1.,  1.,  4.],
       [ 0., 36.,  4.,  0., 16.],
       [16., 64.,  4., 16.,  0.]])

In [29]:
# Do the same thing with np.square()
np.square(arr10)

array([[25., 36.,  1.,  1.,  4.],
       [ 0., 36.,  4.,  0., 16.],
       [16., 64.,  4., 16.,  0.]])

In [30]:
# Find the mean of the latest array using np.mean()
np.mean(arr10)

2.8666666666666667

In [31]:
# Find the maximum of the latest array using np.max()
np.max(arr10)

8.0

In [32]:
# Find the minimum of the latest array using np.min()
np.mean(arr10)

2.8666666666666667

In [33]:
# Find the standard deviation of the latest array
np.std(arr10)

2.578543947441829

In [34]:
# Find the variance of the latest array
np.var(arr10)

6.648888888888889

In [35]:
# Reshape the latest array to (3, 5, 1)
arr10.reshape(3,5,1)

array([[[ 5.],
        [ 6.],
        [ 1.],
        [-1.],
        [ 2.]],

       [[ 0.],
        [ 6.],
        [ 2.],
        [ 0.],
        [ 4.]],

       [[ 4.],
        [ 8.],
        [ 2.],
        [ 4.],
        [ 0.]]])

In [36]:
arr10

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [37]:
# Transpose the latest array
arr10.T

array([[ 5.,  0.,  4.],
       [ 6.,  6.,  8.],
       [ 1.,  2.,  2.],
       [-1.,  0.,  4.],
       [ 2.,  4.,  0.]])

What does the transpose do?

In [38]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr11 = np.random.randint(0,10,size=(3,3))
arr12 = np.random.randint(0,10,size=(3,2))

In [39]:
arr11

array([[9, 1, 9],
       [3, 7, 6],
       [8, 7, 4]])

In [40]:
arr12

array([[1, 4],
       [7, 9],
       [8, 8]])

In [41]:
# Perform a dot product on the two newest arrays you created
arr11.dot(arr12)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [42]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr13 = np.random.randint(0,10,size=(4,3))
arr14 = np.random.randint(0,10,size=(4,3))

In [43]:
arr13

array([[0, 8, 6],
       [8, 7, 0],
       [7, 7, 2],
       [0, 7, 2]])

In [44]:
arr14

array([[2, 0, 4],
       [9, 6, 9],
       [8, 6, 8],
       [7, 1, 0]])

In [45]:
arr14.T

array([[2, 9, 8, 7],
       [0, 6, 6, 1],
       [4, 9, 8, 0]])

In [46]:
# Perform a dot product on the two newest arrays you created
# arr13.dot(arr14)

It doesn't work. How would you fix it?

In [47]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr13.dot(arr14.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [48]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr15 = np.random.randint(0,10,size=(2,5))
arr16 = np.random.randint(0,10,size=(2,5))

In [49]:
arr15

array([[6, 6, 7, 4, 2],
       [7, 5, 2, 0, 2]])

In [50]:
arr16

array([[4, 2, 0, 4, 9],
       [6, 6, 8, 9, 9]])

In [51]:
# Compare the two arrays with '>'
arr15 > arr16

array([[ True,  True,  True, False, False],
       [ True, False, False, False, False]])

What happens when you compare the arrays with `>`?

In [52]:
# Compare the two arrays with '>='
arr15 >= arr16

array([[ True,  True,  True,  True, False],
       [ True, False, False, False, False]])

In [53]:
# Find which elements of the first array are greater than 7
arr15 > 7

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [54]:
# Which parts of each array are equal? (try using '==')
arr15 == arr16

array([[False, False, False,  True, False],
       [False, False, False, False, False]])

In [55]:
# Sort one of the arrays you just created in ascending order
np.sort(arr15)

array([[2, 4, 6, 6, 7],
       [0, 2, 2, 5, 7]])

In [56]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr15)

array([[4, 3, 0, 1, 2],
       [3, 2, 4, 1, 0]], dtype=int64)

In [57]:
arr15

array([[6, 6, 7, 4, 2],
       [7, 5, 2, 0, 2]])

In [58]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr15)

2

In [59]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr15)

8

In [60]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(arr15, axis=0)

array([1, 0, 0, 0, 0], dtype=int64)

In [61]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmax(arr15, axis=1)

array([2, 0], dtype=int64)

In [62]:
# Create an array of normally distributed random numbers
arr17 = np.random.randn(5,3)
arr17

array([[-1.38071702, -0.28080629, -0.05981726],
       [ 0.96117377,  1.79428084,  0.58068954],
       [ 0.29765045, -1.02811577, -1.41859646],
       [ 0.19033698,  0.13575383,  0.60808966],
       [ 0.70498131,  0.36092338, -1.46696789]])

In [63]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr18 = np.linspace(1,100,10)
arr18

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.